### ISSUE TITLE
端口冲突，建议修改mysql映射配置

### ISSUE THREAD

**Issue by tinker-li** [creditease-sec/insight2_docker#1]
ERROR: for web_mysql  Cannot start service web_mysql: Ports are not available: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.

docker-compose.yml第11行"3306:3306"，修改为"3399:3306"可解决此问题。

**Comment by tinker-li** [comment]
docker-compose.yml   9e0e36d

**Comment by tinker-li** [comment]
emmm，也许没有开mysql的同学，不会遇到这个问题。😁

**Comment by CESRC-CreditEase** [comment]
感谢建议，后续会在文档中说明端口映射等相关配置修改的操作方法
