### ISSUE TITLE
请问下用户session过期时间设置是在哪个文件，现在是永不过期。

### ISSUE THREAD

**Issue by Toplong95** [creditease-sec/insight2_docker#22]
只要用户不主动点击退出登录，就一直在线。

**Comment by CESRC-CreditEase** [comment]
暂时没有设置的地方，可以找到文件 `action/user.py` 中有的 `self.set_secure_cookie("__UID__", str(user.id))`，修改成`self.set_secure_cookie("__UID__", str(user.id), expires_days=30)`，expires_days指天数。
