### ISSUE TITLE
最新镜像有问题

### ISSUE THREAD

**Issue by ivybao0628** [creditease-sec/insight2_docker#24]
5 days 作者修改的代码打包到镜像，我使用新镜像之后，在后台管理-组管理出现前端报错，新增角色和查询不显示，报错实例：
![image](https://user-images.githubusercontent.com/13583188/97397284-ddc29a00-1923-11eb-8aff-89fba0b6f563.png)

**Comment by CESRC-CreditEase** [comment]
已修复，请重新拉一遍

**Comment by ivybao0628** [comment]
感谢
