### ISSUE TITLE
最新镜像UP之后卡在这里了

### ISSUE THREAD

**Issue by DDestinys** [creditease-sec/insight2_docker#25]
![image](https://user-images.githubusercontent.com/73631761/97531935-44ad8500-19f0-11eb-8a54-5c352adc0cb4.png)

**Comment by DDestinys** [comment]
![image](https://user-images.githubusercontent.com/73631761/97531961-5727be80-19f0-11eb-9578-b98777c8a95a.png
![擦擦擦](https://user-images.githubusercontent.com/73631761/97532203-c56c8100-19f0-11eb-9889-38a2aa5518e7.png)
)

**Comment by CESRC-CreditEase** [comment]
应该是启动成功了，如果想在后台执行,可以 docker-compose up -d

**Comment by DDestinys** [comment]
后台也不行，前台验证码出不来，我手工搭建了一下可以了，应该是docker redis的原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "creditease-sec/insight2_docker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 下午3:06
收件人:&nbsp;"creditease-sec/insight2_docker"<insight2_docker@noreply.github.com&gt;;
抄送:&nbsp;"Destiny"<838842963@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [creditease-sec/insight2_docker] 最新镜像UP之后卡在这里了 (#25)





 
应该是启动成功了，如果想在后台执行,可以 docker-compose up -d
