### ISSUE TITLE
无法新增用户为审核角色

### ISSUE THREAD

**Issue by ShuailingMa** [creditease-sec/insight2_docker#27]
如果角色为审核角色，新建用户所属的角色不可以选择属于审核角色
![image](https://user-images.githubusercontent.com/37092497/105634513-4ffe3880-5e99-11eb-8c8b-908ad6d5dde7.png)
![image](https://user-images.githubusercontent.com/37092497/105634530-63110880-5e99-11eb-8fa3-e70d15748c88.png)

**Comment by CESRC-CreditEase** [comment]
审核角色用于用户组内成员设置, 在后台-用户-组-管理成员-添加按钮左侧中选择, 感谢支持!
